- hosts: all
  become: true
  tasks:
    - name: add tomcatuser
      user:
        name: tomcat
        shell: /bin/bash/
    - name: get_installer
      get_url:
       url: https://ftp.heanet.ie/mirrors/www.apache.org/dist/tomcat/tomcat-10/v10.0.6/bin/apache-tomcat-10.0.6.tar.gz
       dest: /tmp/
      become: yes
      become_user: root
    - name: copy
      command: cp -p /tmp/apache-tomcat-10.0.6.tar.gz /usr/local/
    - name: install
      unarchive:
       src: /usr/local/apache-tomcat-10.0.6.tar.gz
       dest: /usr/local/
       remote_src: yes
      become: yes
      become_user: root

    - name: Change file ownership, group and permissions
      file:
        path: /usr/local/apache-tomcat-10.0.6
        owner: tomcat
        group: tomcat
        recurse: yes
        state: directory

    - name: make tomcat.service
      file:
        path: /etc/systemd/system/tomcat.service
        state: touch
    - name: edit tomcat.service
      blockinfile:
        dest: /etc/systemd/system/tomcat.service
        insertafter:
        block: |
          [Unit]
          Description = Apache Tomcat 10
          After = syslog.target network.target
          [Service]
          User = tomcat
          Group = tomcat
          Type = oneshot
          PIDFile =/usr/local/apache-tomcat-10.0.6/tomcat.pid
          RemainAfterExit = yes
          ExecStart =/usr/local/apache-tomcat-10.0.6/bin/startup.sh
          ExecStop =/usr/local/apache-tomcat-10.0.6/bin/shutdown.sh
          ExecReStart =/usr/local/apache-tomcat-10.0.6/bin/shutdown.sh;/usr/local/apache-tomcat-10.0.6/bin/startup.sh
          [Install]
          WantedBy = multi-user.target
    - name: chmod 755 tomcat.service
      file:
        path: /etc/systemd/system/tomcat.service
        mode: 0755
    - name: edit tomcat-users.xml
      blockinfile:
        dest: /usr/local/apache-tomcat-10.0.6/conf/tomcat-users.xml
        insertafter: <tomcat-users>
        block: |
          <role rolename = "admin-gui" />
          <role rolename = "manager-gui" />
          <user username = "tomcat" password = "P @ ssw0rd123" roles = "admin-gui, manager-gui" />
    - name: start tomcat
      systemd:
        name: tomcat.service
        state: started
        daemon_reload: yes
        enabled: yes
      become: yes
